version: "3"
services:
  bot:
    image: bot_image
    container_name: "${BOT}"
    build: ./bot
    volumes:
      - ./logs:/var/log/
      - ./bot:/bot
    environment:
      - TOKEN=${TOKEN}
      - RM_HOST=${RM_HOST}
      - RM_PORT=${RM_PORT}
      - RM_USER=${RM_USER}
      - RM_PASSWORD=${RM_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}

  db:
    image: db_image
    container_name: "${DB_HOST}"
    build: ./db
    volumes:
      - ./logs:/var/log/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DB_REPL_USER=${DB_REPL_USER}
      - DB_REPL_PASSWORD=${DB_REPL_PASSWORD}
      - DB_REPL_HOST=${DB_REPL_HOST}.my_network
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}

  db_repl:
    image: db_repl_image
    container_name: "${DB_REPL_HOST}"
    build: ./db_repl
    environment:
      - DB_HOST=${DB_HOST}.my_network
      - DB_PORT=${DB_PORT}
      - DB_REPL_HOST=${DB_REPL_HOST}
      - DB_REPL_PORT=${DB_REPL_PORT}
      - DB_REPL_USER=${DB_REPL_USER}
      - DB_REPL_PASSWORD=${DB_REPL_PASSWORD}

networks:
  default:
    name: my_network
